In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.ones((6,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [13]:
np.random.rand(10)

array([0.81003553, 0.49485777, 0.13482248, 0.90841176, 0.31435173,
       0.48635979, 0.27262755, 0.23417445, 0.87800211, 0.57757942])

In [15]:
np.random.randn(10)

array([-0.76190112,  0.76895561,  0.8266224 , -0.26428768,  1.60219072,
       -0.66731731, -0.48953666,  0.56524037,  1.20451063,  0.12164731])

In [17]:
np.random.randint(5,20,5)

array([16, 12, 16, 19, 10], dtype=int32)

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [28]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

In [34]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr[6]

np.int64(17)

In [41]:
arr[1:5]

array([12, 13, 14, 15])

In [42]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
arr[0]

array([1, 2, 3, 4, 5])

In [44]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [46]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [51]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [52]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [55]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [56]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [57]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [58]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [59]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [60]:
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

In [63]:
arr3=np.arange(1,26).reshape(5,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
arr3+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [65]:
 a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [69]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])

In [70]:
a@b

array([[ 7, 10],
       [15, 22]])

In [71]:
a.T

array([[1, 3],
       [2, 4]])

In [72]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [74]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [79]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [82]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]